image: rust:latest

variables:
  CARGO_HOME: $CI_PROJECT_DIR/.cargo

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .cargo/
    - target/

stages:
  - check
  - test
  - build

check:
  stage: check
  before_script:
    - rustup component add rustfmt clippy
  script:
    - cargo fmt --all -- --check
    - cargo clippy --all-targets --all-features -- -D warnings

test:
  stage: test
  script:
    - cargo test --verbose

build:
  stage: build
  script:
    - cargo build --release
  artifacts:
    paths:
      - target/release/amorce
    expire_in: 1 week
